[package]
name = "ireko"
version = "0.1.0"
edition = "2024"

[dependencies]
flate2 = { version = "1.0", features = ["zlib-ng"], default-features = false }
binrw = { version = "0.14", features = ["std"], default-features = false }
